spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ovzocperakrbvcyoaqqs
spring.datasource.password=507202kcktm

# OAuth2 - Google
spring.security.oauth2.client.registration.google.client-id=430182099521-vubjeb4beo260mt5qeru9531e8tbhegd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

spring.jpa.hibernate.ddl-auto=update